---
- name: Run System role
  ansible.builtin.include_role:
    name: system

- name: Run Projects role
  ansible.builtin.include_role:
    name: projects

- name: Backup restore of relevant data
  ansible.builtin.include_tasks: "{{ task }}"
  loop:
    - setup.yml
    - restore.yml
  loop_control:
    loop_var: task
