---
- name: Check if services folder exists
  ansible.builtin.stat:
    path: "{{ restore_services_dir }}"
  register: restore_services_folder_check

- name: Restore data in services folder using Restic
  ansible.builtin.command:
    cmd: restic restore latest --target {{ restore_services_target }}
  become: false
  become_user: "{{ username }}"
  environment:
    RESTIC_REPOSITORY: "{{ restore_services_restic_repository }}"
    RESTIC_PASSWORD: "{{ restore_restic_password }}"
    AWS_ACCESS_KEY_ID: "{{ restore_aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ restore_aws_secret_access_key }}"
    AWS_DEFAULT_REGION: "auto"
  register: restore_services_result
  changed_when: false
  failed_when: restore_services_result.rc != 0 and 'xattr' not in restore_services_result.stderr
  when: not restore_services_folder_check.stat.exists

- name: Check if nextcloud data folder exists
  ansible.builtin.stat:
    path: "{{ restore_nextcloud_data_dir }}"
  register: restore_nextcloud_data_folder_check

- name: Restore nextcloud data using Restic
  ansible.builtin.command:
    cmd: restic restore latest --target {{ restore_nextcloud_target }}
  become: false
  become_user: "{{ username }}"
  environment:
    RESTIC_REPOSITORY: "{{ restore_nextcloud_restic_repository }}"
    RESTIC_PASSWORD: "{{ restore_restic_password }}"
    AWS_ACCESS_KEY_ID: "{{ restore_aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ restore_aws_secret_access_key }}"
    AWS_DEFAULT_REGION: "auto"
  register: restore_nextcloud_result
  changed_when: false
  failed_when: restore_nextcloud_result.rc != 0 and 'xattr' not in restore_nextcloud_result.stderr
  when: not restore_nextcloud_data_folder_check.stat.exists
