---
- name: Converge
  hosts: all
  gather_facts: true
  become: true  # TODO: remove this later from all the tests
  tasks:
    - name: Test services role
      ansible.builtin.include_role:
        name: services
