---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: test_ansible_role_services
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg

verifier:
  name: ansible
