- name: Play for configuring home server using ansible-pull
  hosts: localhost
  connection: local
  become: true

  vars:
    username: diego
    shell: /bin/bash

  pre_tasks:
    - name: Install Ansible Galaxy packages
      ansible.builtin.command: ansible-galaxy install -r requirements.yml

  roles:
    - role: system
    - role: development
