- name: Play for configuring home server
  hosts: home_server
  become: true
  gather_facts: false

  vars:
    username: diego
    shell: /bin/bash

  roles:
    - role: system
    - role: development
    - role: projects
    # TODO: add services role
