# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config.json

version: "1"

## Base Configurations
global:
  initialize: true
  min-memory: 200

groups:
  auto-backup:
    - s_tier
    - a_tier
    - services
  manual-backup:
    - b_tier
    - c_tier

## Configuration profiles
default:
  password-file: "{{ .ConfigDir }}/.resticprofile_key"

  env:
    AWS_SECRET_ACCESS_KEY: "{{ .Env.AWS_SECRET_ACCESS_KEY }}"
    AWS_ACCESS_KEY_ID: "{{ .Env.AWS_ACCESS_KEY_ID }}"

  check-before: true
  exclude-caches: true
  one-file-system: false
  no-error-on-warning: true
  verbose: true

  backup:
    exclude-caches: true
    exclude:
      - /**/cache
      - /**/.venv
      - /**/logs

  retention:
    before-backup: false
    after-backup: true
    tag: true

    keep-daily: 1
    keep-weekly: 2
    keep-monthly: 1

s_tier:
  inherit: default
  repository: "s3:{{ .Env.AWS_BUCKET_URL }}/s_tier"

  backup:
    source:
      - /media/hd1/nextcloud/{{ .Env.USERNAME }}/files/Documents
      - /media/hd1/nextcloud/{{ .Env.USERNAME }}/files/Notes
      - /media/hd1/nextcloud/{{ .Env.USERNAME }}/files/Projects
      - /media/hd1/nextcloud/{{ .Env.USERNAME }}/files/Work
    tag:
      - s_tier
    schedule: 02:00
    schedule-permission: system

services:
  inherit: default
  repository: "s3:{{ .Env.AWS_BUCKET_URL }}/services"

  backup:
    source:
      - /home/{{ .Env.USERNAME }}/services_data
    tag:
      - services
    schedule: 03:00
    schedule-permission: system

a_tier:
  inherit: default
  repository: "local:/media/hd1/backups/a_tier"

  backup:
    source:
      - /media/hd1/nextcloud
      - /media/hd1/photo_library
      - /media/hd1/backups/db_dumps
      - /home/{{ .Env.USERNAME }}/study
      - /home/{{ .Env.USERNAME }}/.bashrc
    tag:
      - a_tier
    schedule: Tue,Thu,Sat 04:00
    schedule-permission: system

b_tier:
  inherit: default
  repository: "local:/mnt/hdd/backups/b_tier"

  backup:
    source:
      - /media/hd1/nextcloud
      - /media/hd1/photo_library
    tag:
      - b_tier

c_tier:
  inherit: b_tier
  repository: "sftp:laptop:Backups/restic/c_tier"

  backup:
    tag:
      - c_tier
