---
projects_git_username: Diego Heer
projects_git_email: diegojonathanheer@gmail.com

projects_github_owner: DiegoHeer
projects_github_repos:
  - gitops-homelab
  - money-metrics
  - financial-organizer
  - zeta
