---
- name: Run System role
  ansible.builtin.include_role:
    name: system

- name: General tasks for GUI usage
  ansible.builtin.include_tasks: "{{ task }}"
  loop:
    - packages.yml
  loop_control:
    loop_var: task
