---
- name: Add the Solaar Unifying (Logitech) apt repository
  ansible.builtin.apt_repository:
    repo: ppa:solaar-unifying/stable
    state: present

- name: Install GUI apt packages
  ansible.builtin.package:
    name:
      - gnome-software-plugin-flatpak
      - solaar
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install flatpak packages
  community.general.flatpak:
    name:
      - com.nextcloud.desktopclient.nextcloud
      - com.github.johnfactotum.Foliate
    state: present
    method: system

- name: Install snap packages
  community.general.snap:
    name:
      - bing-wall
      - bitwarden
      - code
      - gtk-common-themes
      - obsidian
      - onlyoffice-desktopeditors
      - spotify
      - vlc
      - whatsapp-linux-app
      - vivaldi
    state: present

- name: Check if Surfshark is installed
  ansible.builtin.stat:
    path: /bin/surfshark
  register: surfshark_check

- name: Get Surfshark installer
  ansible.builtin.get_url:
    url: https://downloads.surfshark.com/linux/debian-install.sh
    dest: /tmp/surfshark-install.sh
    mode: "0755"
  when: not surfshark_check.stat.exists

- name: Install Surfshark
  ansible.builtin.command: /tmp/surfshark-install.sh
  changed_when: not surfshark_check.stat.exists
  when: not surfshark_check.stat.exists
