- name: Install GNOME software plugin for flatpak
  ansible.builtin.package:
    name: gnome-software-plugin-flatpak
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install flatpak packages
  community.general.flatpak:
    name: 
      - com.nextcloud.desktopclient.nextcloud
      - com.github.johnfactotum.Foliate
    state: present
    method: system

- name: Install snap packages
  community.general.snap:
    name:
      - bing-wall
      - bitwarden
      - code
      - gtk-common-themes
      - obsidian
      - onlyoffice-desktopeditors
      - spotify
      - vlc
      - whatsapp-linux-app
      - vivaldi
    state: present

