---
- name: Check if Linuxbrew is installed
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: system_linuxbrew_check

- name: Ensure Linuxbrew prefix directory exists
  ansible.builtin.file:
    path: /home/linuxbrew/.linuxbrew
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  when: not system_linuxbrew_check.stat.exists

- name: Get Linuxbrew installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/install-linuxbrew.sh
    mode: "0755"
  when: not system_linuxbrew_check.stat.exists

- name: Install Linuxbrew
  ansible.builtin.command: /tmp/install-linuxbrew.sh
  become: true
  become_user: "{{ username }}"
  environment:
    NONINTERACTIVE: "1"
  changed_when: not system_linuxbrew_check.stat.exists
  when: not system_linuxbrew_check.stat.exists

- name: Add Linuxbrew to PATH in bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.bashrc
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
  notify: Apply updated PATH

- name: Install Linuxbrew packages
  community.general.homebrew:
    name:
      - ast-grep
      - gh
      - claude-code
      - tree
      - sops
    state: present
  become: true
  become_user: "{{ username }}"
