---
- name: System tasks
  ansible.builtin.include_tasks: "{{ task }}"
  loop:
    - user.yml
    - settings.yml
    - packages.yml
    - tmux.yml
    - oh_my_posh.yml
    - tailscale.yml
  loop_control:
    loop_var: task
