---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: true

- name: Install apt packages
  ansible.builtin.package:
    name:
      - net-tools
      - speedtest-cli
      - software-properties-common
      - glances
      - zip
      - unzip
      - curl
      - flatpak
      - snapd
      - build-essential
      - procps
      - file
      - git
      - age
      - sops
    state: present
