---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install apt packages
  ansible.builtin.package:
    name: "{{ system_packages }}"
    state: present

- name: Check if oh-my-posh is installed
  ansible.builtin.stat:
    path: /bin/oh-my-posh
  register: oh_my_posh_check

- name: Get oh-my-posh installer
  ansible.builtin.get_url:
    url: https://ohmyposh.dev/install.sh
    dest: /tmp/install-oh-my-posh.sh
    mode: "0755"
  when: not oh_my_posh_check.stat.exists

- name: Install oh-my-posh
  ansible.builtin.command: /tmp/install-oh-my-posh.sh -d /bin
  changed_when: not oh_my_posh_check.stat.exists
  when: not oh_my_posh_check.stat.exists
