---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install apt packages
  ansible.builtin.package:
    name:
      - net-tools
      - speedtest-cli
      - software-properties-common
      - glances
      - zip
      - unzip
      - curl
      - flatpak
      - snapd
    state: present
