---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install apt packages
  ansible.builtin.package:
    name: "{{ system_packages }}"
    state: present
