services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:v0.6.13
    network_mode: service:open-webui-tailscale
    volumes:
      - /home/${USERNAME}/services_data/open-webui/data:/app/backend/data
    depends_on:
      open-webui-tailscale:
        condition: service_healthy

  open-webui-tailscale:
    image: tailscale/tailscale:v1.84.0
    container_name: open-webui-tailscale
    hostname: open-webui
    environment:
      # Valid until 30/08/2025
      - TS_AUTHKEY=${OPEN_WEBUI_TAILSCALE_AUTHKEY}
      - TS_SERVE_CONFIG=/config/open-webui.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /home/${USERNAME}/services_data/open-webui-tailscale/state:/var/lib/tailscale
      - /home/${USERNAME}/services_data/open-webui-tailscale/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
