services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.15-ubuntu2204
    container_name: mongodb
    network_mode: service:mongo-tailscale
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    volumes:
      - /media/hd1/databases/mongodb/data:/data/db
    depends_on:
      - mongo-tailscale
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  mongo-tailscale:
    image: tailscale/tailscale:v1.80.3
    container_name: mongo-tailscale
    restart: unless-stopped
    hostname: database
    environment:
      # Valid until 2025-02-28
      - TS_AUTHKEY=${MONGODB_TAILSCALE_AUTHKEY}
      - TS_ACCEPT_DNS=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /home/${USERNAME}/services_data/mongo-tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - /lib/modules:/lib/modules
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@database.amarok-eagle.ts.net:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ping", "-c", "3", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # https://www.reddit.com/r/selfhosted/comments/1eo7knj/guide_obsidian_with_free_selfhosted_instant_sync/
  obsidian-livesync:
    container_name: obsidian-livesync
    image: couchdb:3.4.3
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0022
      - TZ=Europe/Amsterdam
      - COUCHDB_USER=obsidian
      - COUCHDB_PASSWORD=obsidian
    volumes:
      - /home/${USERNAME}/services_data/obsidian-livesync/data:/opt/couchdb/data
      - /home/${USERNAME}/services_data/obsidian-livesync/etc/local.d:/opt/couchdb/etc/local.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://obsidian:obsidian@localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
