include:
  - media.yml
  - monitoring.yml
  - photos.yml
  - databases.yml
  - cloud_management.yml
  - tools.yml
  # - remote_access.yml

networks:
  default:
    name: home_server_network
    driver: bridge

services:
  tailscale:
    image: tailscale/tailscale:v1.80.0
    container_name: tailscale
    restart: unless-stopped
    hostname: home_server
    environment:
      - TS_AUTHKEY=tskey-auth-kLYiuNzVZw11CNTRL-mCMiusCkHBFSxeNbYdbXBFsWi49LtPG6
      - TS_ACCEPT_DNS=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /home/diego/services_data/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin

  # Reference: https://www.youtube.com/watch?v=qlcVx-k-02E
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:2.12.3"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/diego/services_data/nginx-proxy-manager/data:/data
      - /home/diego/services_data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /home/diego/services_data/nginx-proxy-manager/logrotate.custom:/etc/logrotate.d/nginx-proxy-manager
    depends_on:
      - tailscale

  homarr:
    container_name: homarr
    restart: unless-stopped
    image: ghcr.io/homarr-labs/homarr:v1.6.0
    ports:
      - 7575:7575
    volumes:
      - /home/diego/services_data/homarr/appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_ENCRYPTION_KEY=ff0ba58c92e92d17d00df517aafa3cff9362a170b1076820528ddbd347a91fce

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.32.0
    restart: unless-stopped
    ports:
      - 8005:80/tcp
    volumes:
      - /media/hd1:/srv
      - /home/diego:/srv/home
      - /home/diego/services_data/filebrowser/filebrowser.db:/database.db
      - /home/diego/services_data/filebrowser/.filebrowser.json:/.filebrowser.json
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PUID=1000
      - PGID=1000
    entrypoint:
      - /filebrowser
    logging:
      driver: json-file
      options: {}
