include:
  - media.yml
  - monitoring.yml
  - photos.yml
  - databases.yml
  - cloud_management.yml
  - tools.yml

networks:
  default:
    name: home_server_network
    driver: bridge

services:
  # Reference: https://www.youtube.com/watch?v=qlcVx-k-02E
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.3
    container_name: nginx-proxy-manager
    restart: unless-stopped
    # network_mode: service:tailscale
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 443:443
      - 80:80
      - 81:81
    volumes:
      - /home/${USERNAME}/services_data/nginx-proxy-manager/data:/data
      - /home/${USERNAME}/services_data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /home/${USERNAME}/services_data/nginx-proxy-manager/logrotate.custom:/etc/logrotate.d/nginx-proxy-manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3

  homarr:
    container_name: homarr
    restart: unless-stopped
    image: ghcr.io/homarr-labs/homarr:v1.18.1
    volumes:
      - /home/${USERNAME}/services_data/homarr/appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY}
    healthcheck:
      test: ["CMD-SHELL", "homarr --version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.32.0
    restart: unless-stopped
    volumes:
      - /media/hd1:/srv
      - /home/${USERNAME}:/srv/home
      - /home/${USERNAME}/services_data/filebrowser/filebrowser.db:/database.db
      - /home/${USERNAME}/services_data/filebrowser/.filebrowser.json:/.filebrowser.json
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PUID=1000
      - PGID=1000
    entrypoint:
      - /filebrowser
    logging:
      driver: json-file
      options: {}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.3
    volumes:
      - /home/${USERNAME}/services_data/glance/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
