services:
  ifo-backend:
    container_name: ifo-backend
    image: ghcr.io/diegoheer/financial-organizer-backend:latest
    env_file:
      - /home/diego/projects/financial-organizer/src/backend/.prod.env
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      ifo-database:
        condition: service_healthy

  ifo-frontend:
    container_name: ifo-frontend
    image: ghcr.io/diegoheer/financial-organizer-frontend:latest
    env_file:
      - /home/diego/projects/financial-organizer/src/frontend/.prod.env
    depends_on:
      ifo-backend:
        condition: service_healthy

  ifo-database:
    container_name: ifo-database
    image: postgres:15.2
    env_file:
      - /home/diego/projects/financial-organizer/src/backend/.prod.env
    volumes:
      - ifo-database-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s

volumes:
  ifo-database-data:
