services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:10.10.5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/hd1/media/tvshows:/data/tvshows
      - /media/hd1/media/movies:/data/movies
      - /media/hd1/media/animes:/data/animes
      - /home/${USERNAME}/services_data/jellyfin/config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  jellyseerr:
    image: fallenbagel/jellyseerr:2.3.0
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Amsterdam
    volumes:
      - /home/${USERNAME}/services_data/jellyseerr/config:/app/config
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5055/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn:5.3.1
    restart: unless-stopped
    environment:
      - OPENVPN_PROVIDER=SURFSHARK
      - OPENVPN_CONFIG=nl-ams.prod.surfshark.com_tcp,be-bru.prod.surfshark.com_tcp.ovpn
      - OPENVPN_USERNAME=${TRANSMISSION_OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${TRANSMISSION_OPENVPN_PASSWORD}
      - LOCAL_NETWORK=${TRANSMISSION_LOCAL_NETWORK}
      - TRANSMISSION_WEB_UI=transmission-web-control
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    volumes:
      - /media/hd1/downloads/data:/data
      - /home/${USERNAME}/services_data/transmission-openvpn/config/transmission-home:/config/transmission-home
      - /home/${USERNAME}/services_data/transmission-openvpn/config/openvpn-credentials.txt:/config/openvpn-credentials.txt
      - /home/${USERNAME}/services_data/transmission-openvpn/config/transmission-credentials.txt:/config/transmission-credentials.txt
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/transmission/web/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/${USERNAME}/services_data/prowlarr/config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:4.0.13
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Amsterdam
    volumes:
      - /home/${USERNAME}/services_data/sonarr/config:/config
      - /media/hd1/media/tvshows:/data/tvshows
      - /media/hd1/media/animes:/data/animes
      - /media/hd1/downloads/data/completed:/data/completed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.18.4
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Amsterdam
    volumes:
      - /home/${USERNAME}/services_data/radarr/config:/config
      - /media/hd1/media/movies:/data/movies
      - /media/hd1/downloads/data/completed:/data/completed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:1.5.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/${USERNAME}/services_data/bazarr/config:/config
      - /media/hd1/media/movies:/movies
      - /media/hd1/media/tvshows:/tv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
