services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:0.10.1
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /home/${USERNAME}/services_data/beszel:/beszel_data

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:0.10.2
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/hd1/.beszel:/extra-filesystems/sdb1:ro
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGZ70crWOkNO8ZFv9Ow2Daz4eaGU4bEYGsVXowTbHs1A"
