services:
  backend:
    container_name: backend
    image: ghcr.io/diegoheer/financial-organizer-backend:latest
    env_file:
      - /home/diego/projects/financial-organizer/src/backend/.prod.env
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    image: ghcr.io/diegoheer/financial-organizer-frontend:latest
    env_file:
      - /home/diego/projects/financial-organizer/src/frontend/.prod.env
    depends_on:
      backend:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15.2
    env_file:
      - /home/diego/projects/financial-organizer/src/backend/.prod.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s

volumes:
  postgres-data:
