services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.129.0
    extends:
      file: /home/${USERNAME}/services_data/immich/hwaccel.transcoding.yml
      service: quicksync
    volumes:
      - /media/hd1/photo_library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.129.0
    restart: unless-stopped
    volumes:
      - model-cache:/cache
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine3.21
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.4.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: immich
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immich-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='immich' --username='postgres' || exit 1; Chksum="$$(psql --dbname='immich' --username='postgres' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]

volumes:
  model-cache:
  immich-db:
