services:
  guacamole-d:
    container_name: guacamole-d
    image: guacamole/guacd:1.5.5
    restart: unless-stopped
    networks:
      guac-net:
        ipv4_address: 172.30.0.2

  guacamole-web:
    container_name: guacamole-web
    image: guacamole/guacamole:1.5.5
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: guacamole_db
      MYSQL_HOSTNAME: 172.30.0.4
      MYSQL_PASSWORD: admin
      MYSQL_USER: guacamole_user
      GUACD_HOSTNAME: 172.30.0.2
      WEBAPP_CONTEXT: 'ROOT'
    depends_on:
      - guacamole-sql
      - guacamole-d
    networks:
      guac-net:

  guacamole-sql:
    container_name: guacamole-sql
    image: mysql:9.2.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      guac-net:
        ipv4_address: 172.30.0.4

volumes:
  dbdata:

networks:
  guac-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/16"
