services:
  olivetin:
    container_name: olivetin
    restart: unless-stopped
    image: jamesread/olivetin:2025.2.21
    volumes:
      - /home/${USERNAME}/services_data/olivetin/config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/api/readyz"]
      interval: 10s
      timeout: 5s
      retries: 5

  cup:
    container_name: cup
    image: ghcr.io/sergi0g/cup:latest
    command: serve -p 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:0.44.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/info/status"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 15s

  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:v2.9.3
    environment:
      - PUID=1000
      - PGID=1000
      - NEXTAUTH_URL=http://linkwarden:3000/api/v1/auth
      - NEXTAUTH_SECRET=linkwarden_secret_password
      - DATABASE_URL=postgresql://postgres:postgres@linkwarden-db:5432/postgres
    volumes:
      - /home/${USERNAME}/services_data/linkwarden/data:/data/data
    depends_on:
      linkwarden-db:
        condition: service_healthy

  linkwarden-db:
    container_name: linkwarden_db
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/${USERNAME}/services_data/linkwarden/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
