services:
  olivetin:
    container_name: olivetin
    restart: unless-stopped
    image: jamesread/olivetin:2025.4.22
    volumes:
      - /home/${USERNAME}/services_data/olivetin/config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/api/readyz"]
      interval: 10s
      timeout: 5s
      retries: 5

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USERNAME}/services_data/dozzle:/data
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

  cup:
    container_name: cup
    image: ghcr.io/sergi0g/cup:latest
    command: serve -p 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:0.45.6
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/info/status"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 15s

  grist:
    container_name: grist
    image: gristlabs/grist:1.5.1
    environment:
        - PORT=9999
    volumes:
        - /home/${USERNAME}/services_data/glance/persist:/persist
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/status"]
      interval: 30s
      retries: 3
      timeout: 5s
      start_period: 10s
      start_interval: 5s

  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:v2.8.0
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /home/${USERNAME}/services_data/mealie:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
      BASE_URL: mealie.dynabase.xyz
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  portracker:
    container_name: portracker
    image: mostafawahied/portracker:latest
    network_mode: "host"
    volumes:
      - /home/${USERNAME}/services_data/portracker/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DATABASE_PATH=/data/portracker.db
      - PORT=4999

  mazanoke:
    container_name: mazanoke
    image: ghcr.io/civilblur/mazanoke:latest

  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:1.106.3
    volumes:
      - /home/${USERNAME}/services_data/n8n/data:/data
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - TZ=Europe/Amsterdam
      - GENERIC_TIMEZONE=Europe/Amsterdam

  docuseal:
    container_name: docuseal
    image: docuseal/docuseal:latest
