services:
  # Reference: https://www.youtube.com/watch?v=qlcVx-k-02E
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.14.0
    container_name: nginx-proxy-manager
    restart: unless-stopped
    dns:
      - 127.0.0.11
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 443:443
      - 80:80
      - 81:81
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ./nginx-proxy-manager/logrotate.custom:/etc/logrotate.d/nginx-proxy-manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3

  cloudflare_tunnel:
    container_name: cloudflare_tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    environment:
      TUNNEL_METRICS: "0.0.0.0:60123"
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  default:
    external: true
    name: home_server_network
