---
restore_services_dir: /home/{{ username }}/services
restore_services_target: /home/{{ username }}
restore_nextcloud_data_dir: /media/hd1/nextcloud/{{ username }}/files
restore_nextcloud_target: /media/hd1
