#!/bin/bash
set -euo pipefail

# Ensure -x is disabled so secrets aren't accidentally printed
set +x

TAILSCALE_API_RESPONSE=$(curl --retry 5 --retry-max-time 120 --silent \
                         -d "client_id=${TAILSCALE_CLIENT_ID}" \
                         -d "client_secret=${TAILSCALE_CLIENT_SECRET}" \
                         "https://api.tailscale.com/api/v2/oauth/token")

TAILSCALE_API_TOKEN=$(echo "${TAILSCALE_API_RESPONSE}" | jq -r '.access_token')

if [[ "${TAILSCALE_API_TOKEN}" == 'null' ]]
then
    >&2 echo 'ERROR: Tailscale API returned an invalid API token, aborting!'
    >&2 echo
    >&2 echo "${TAILSCALE_API_RESPONSE}"
    exit 1
fi

echo "${TAILSCALE_API_TOKEN}"