---
- name: Authorize target SSH public key with GitHub
  community.general.github_deploy_key:
    name: ansible_key
    key: "{{ ssh_key.public_key }}"
    read_only: false
    state: present
    owner: "{{ projects_github_owner }}"
    repo: "{{ repo }}"
    token: "{{ github_access_token }}"
  loop: "{{ projects_github_repos }}"
  loop_control:
    loop_var: repo

- name: Clone Github repos
  become: false
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "git@github.com:{{ projects_github_owner }}/{{ repo }}.git"
    dest: "/home/{{ username }}/projects/{{ repo }}"
    key_file: "{{ ssh_key.filename }}"
    accept_newhostkey: true
    clone: true
    version: main
  loop: "{{ projects_github_repos }}"
  loop_control:
    loop_var: repo
