---
- name: Authorize target SSH public key with GitHub
  community.general.github_key:
    name: ansible_key
    pubkey: "{{ projects_github_ssh_key.public_key }}"
    state: present
    force: true
    token: "{{ github_access_token }}"

- name: Clone Github repos
  become: false
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "git@github.com:{{ projects_github_owner }}/{{ repo }}.git"
    dest: "/home/{{ username }}/projects/{{ repo }}"
    key_file: "{{ projects_github_ssh_key.filename }}"
    accept_newhostkey: true
    clone: true
    version: main
  loop: "{{ projects_github_repos }}"
  loop_control:
    loop_var: repo
