---
- name: Install pip packages for Gitlab
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: python-gitlab
      - name: requests

- name: Authorize target SSH public key with Gitlab
  community.general.gitlab_deploy_key:
    api_url: https://gitlab.com
    api_token: "{{ gitlab_access_token }}"
    project: "Dynatron/{{ repo }}"
    title: ansible_key
    state: present
    can_push: true
    key: "{{ ssh_key.public_key }}"
  loop: "{{ projects_gitlab_repos }}"
  loop_control:
    loop_var: repo

- name: Clone Gitlab repos
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: git@gitlab.com:Dynatron/{{ repo }}.git
    clone: true
    accept_newhostkey: true
    dest: "/home/{{ username }}/projects/{{ repo }}"
  loop: "{{ projects_gitlab_repos }}"
  loop_control:
    loop_var: repo
