---
- name: General tasks for setting up git and checking out repositories
  ansible.builtin.include_tasks: "{{ task }}"
  loop:
    - settings.yml
    - gitlab.yml
    - github.yml
  loop_control:
    loop_var: task
