---
- name: Check if git is installed
  ansible.builtin.stat:
    path: /usr/bin/git
  register: git_check

- name: Install git
  ansible.builtin.package:
    name: git
    state: present
    update_cache: true
  when: not git_check.stat.exists

- name: Configure git user name
  become: false
  become_user: "{{ username }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ projects_git_username }}"

- name: Configure git email
  become: false
  become_user: "{{ username }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ projects_git_email }}"

- name: Configure git default branch name
  become: false
  become_user: "{{ username }}"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Configure git auto setup remote
  become: false
  become_user: "{{ username }}"
  community.general.git_config:
    name: push.autoSetupRemote
    scope: global
    value: true

- name: Configure git default editor
  become: false
  become_user: "{{ username }}"
  community.general.git_config:
    name: core.editor
    scope: global
    value: nano

- name: Ensure .ssh directory has correct permissions
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"

- name: Generate target SSH key for accessing Github
  community.crypto.openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    owner: "{{ username }}"
    group: "{{ username }}"
  register: ssh_key

- name: Create projects folder
  ansible.builtin.file:
    path: "/home/{{ username }}/projects"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
