- name: Check if git is installed
  ansible.builtin.command: git --version
  register: git_check
  ignore_errors: true

- name: Install git
  ansible.builtin.package:
    name: git
    state: present
    update_cache: yes
  when: git_check.rc != 0

- name: Configure git user name
  ansible.builtin.command: git config --global user.name "{{ git_username }}"
  become_user: "{{ username }}"

- name: Configure git email
  ansible.builtin.command: git config --global user.email "{{ git_email }}"
  become_user: "{{ username }}"

- name: Ensure .ssh directory has correct permissions
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"

- name: Generate target SSH key for accessing Gitlab and Github
  ansible.builtin.openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    owner: "{{ username }}"
    group: "{{ username }}"
  register: ssh_key

- name: Create projects folder
  ansible.builtin.file:
    path: "/home/{{ username }}/projects"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
