---
- name: Play for configuring home server
  hosts: home_server
  become: true

  vars:
    username: diego

  roles:
    - role: system
    - role: development
    - role: projects
    - role: services
