---
- name: Pull and start docker compose services
  environment:
    USERNAME: "{{ username }}"
    HOMARR_SECRET_ENCRYPTION_KEY: "{{ services_homarr_secret_encryption_key }}"
    MONGODB_TAILSCALE_AUTHKEY: "{{ services_mongodb_tailscale_authkey }}"
    TRANSMISSION_OPENVPN_USERNAME: "{{ services_transmission_openvpn_username }}"
    TRANSMISSION_OPENVPN_PASSWORD: "{{ services_transmission_openvpn_password }}"
    TRANSMISSION_LOCAL_NETWORK: "{{ services_transmission_local_network }}"
  block:
    - name: Pull docker compose images
      community.docker.docker_compose_v2_pull:
        project_src: "{{ services_docker_src }}"

    - name: Start docker compose services
      community.docker.docker_compose_v2:
        project_src: "{{ services_docker_src }}"
        state: present
