---
- name: Find all docker compose service directories
  ansible.builtin.find:
    paths: "{{ services_docker_src }}"
    file_type: directory
    depth: 1
  register: services_dirs
  when: services_run_compose

- name: Pull and start docker compose stacks
  community.docker.docker_compose_v2:
    project_src: "{{ item.path }}"
    pull: always
    state: present
  loop: "{{ services_dirs.files | default([]) }}"
  loop_control:
    label: "{{ item.path | basename }}"
  become: true
  become_user: "{{ username }}"
  when: services_run_compose
