---
- name: Run System role
  ansible.builtin.include_role:
    name: system

- name: Run Projects role
  ansible.builtin.include_role:
    name: projects

- name: Run Restore role
  ansible.builtin.include_role:
    name: restore

- name: Home Server docker services setup
  ansible.builtin.include_tasks: "{{ task }}"
  loop:
    - checks.yml
    - packages.yml
    - compose.yml
  loop_control:
    loop_var: task
