---
- name: Converge
  hosts: all
  gather_facts: true
  become: true  # TODO: remove this later from all the tests
  tasks:
    - name: Test projects role
      ansible.builtin.include_role:
        name: projects
  vars:
    username: diego
