services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:0.18.2
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /home/${USERNAME}/services_data/beszel:/beszel_data
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 5s

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:0.18.2
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/hd1/.beszel:/extra-filesystems/sdb1:ro
      - /media/hd2/.beszel:/extra-filesystems/sdd1:ro
      - /media/hd3/.beszel:/extra-filesystems/sde1:ro
      - /home/${USERNAME}/services_data/beszel/agent_data:/var/lib/beszel-agent
    environment:
      LISTEN: 45876
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
      HUB_URL: https://beszel.dynabase.nl
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      beszel:
        condition: service_healthy

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - /home/${USERNAME}/services_data/adguardhome/conf:/opt/adguardhome/conf
      - /home/${USERNAME}/services_data/adguardhome/work:/opt/adguardhome/work
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "53"]
      interval: 45s
      timeout: 30s
      retries: 3

  portracker:
    container_name: portracker
    image: mostafawahied/portracker:latest
    restart: unless-stopped
    pid: "host"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/${USERNAME}/services_data/portracker/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4999/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s


networks:
  default:
    external: true
    name: home_server_network